Airlines/AirlinesWeb/Models/Airline/AirlineViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AirlinesWeb.Models.Airline;

public class AirlineViewModel
{
    [Key]
    public int ID { get; set; }

    [Required(ErrorMessage = "Name is required")]
    [StringLength(5, ErrorMessage = "Name should be at most 5 characters long")]
    [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "Name should only contain letters and spaces")]
    public string? Name { get; set; }

    [DataType(DataType.Date)]
    [Required(ErrorMessage = "Founded date is required")]
    public DateOnly? Founded { get; set; }

    [Required(ErrorMessage = "Fleet size is required")]
    [Range(1, int.MaxValue, ErrorMessage = "Fleet size should be a positive integer")]
    public int FleetSize { get; set; }

    [Required(ErrorMessage = "Description is required")]
    [StringLength(1000, ErrorMessage = "Description should be at most 1000 characters long")]
    [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "Description should only contain letters and spaces")]
    public string? Description { get; set; }
}

Airlines/AirlinesWeb/Controllers/AirlineController.cs
using Airlines.Business.Services;
using Airlines.Business.Utils;
using Airlines.Persistence.Basic.DTO;
using Airlines.Persistence.Basic.EntitiesDB;
using AirlinesWeb.Models.Airline;
using Microsoft.AspNetCore.Mvc;

namespace AirlinesWeb.Controllers;

#pragma warning disable IDE0290 // Use primary constructor
#pragma warning disable IDE0021 // Use expression body for constructor

public class AirlineController : Controller
{
    private readonly IAirlineService _airlineService;

    public AirlineController(IAirlineService airlineService)
    {
        _airlineService = airlineService;
    }

    public async Task<IActionResult> Index()
    {
        var nameFilterValue = HttpContext.Request.Query["nameFilter"].ToString();
        var foundedFilterValue = HttpContext.Request.Query["foundedFilter"].ToString();
        var fleetSizeFilterValue = HttpContext.Request.Query["fleetSizeFilter"].ToString();
        var descriptionFilterValue = HttpContext.Request.Query["descriptionFilter"].ToString();
        var searchValue = HttpContext.Request.Query["search"].ToString();
        var searchFilterValue = HttpContext.Request.Query["searchFilter"].ToString();

        List<Airline> allAirlines = !string.IsNullOrEmpty(searchValue)
            ? await _airlineService.GetAllAirlinesFromDB(searchValue, searchFilterValue)
            : await _airlineService.GetAllAirlinesFromDB();

        allAirlines = ServicesUtils.ApplySorting(allAirlines, nameFilterValue, x => x.Name);
        allAirlines = ServicesUtils.ApplySorting(allAirlines, foundedFilterValue, x => x.Founded!);
        allAirlines = ServicesUtils.ApplySorting(allAirlines, fleetSizeFilterValue, x => x.FleetSize);
        allAirlines = ServicesUtils.ApplySorting(allAirlines, descriptionFilterValue, x => x.Description);

        List<AirlineViewModel> allAirlinesViewModel = allAirlines.Select(x => new AirlineViewModel
        {
            ID = x.ID,
            Name = x.Name,
            Founded = x.Founded,
            FleetSize = x.FleetSize,
            Description = x.Description
        }).ToList();


        return View((allAirlinesViewModel, new AirlineViewModel()));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] AirlineViewModel airlineViewModel)
    {
        AirlineDTO airlineDTO = new AirlineDTO(
            airlineViewModel.Name,
            airlineViewModel.Founded,
            airlineViewModel.FleetSize,
            airlineViewModel.Description
        );

        List<Airline> allAirlines = await _airlineService.GetAllAirlinesFromDB();

        List<AirlineViewModel> allAirlinesViewModel = allAirlines.Select(x => new AirlineViewModel
        {
            ID = x.ID,
            Name = x.Name,
            Founded = x.Founded,
            FleetSize = x.FleetSize,
            Description = x.Description
        }).ToList();

        if (!ModelState.IsValid)
        {
            ViewBag.Error = "Invalid airline create entity";

            return View(nameof(Index), (allAirlinesViewModel, airlineViewModel));
        }

        if (await _airlineService.AddAirlineToDB(airlineDTO) == null)
        {
            ViewBag.Error = "Invalid airline create entity";
            return View(nameof(Index), (allAirlinesViewModel, airlineViewModel));
        }

        return RedirectToAction(nameof(Index));
    }
}

Airlines/AirlinesWeb/Views/Airline/Index.cshtml
@using AirlinesWeb.Models.Airline;

@model (List<AirlineViewModel>, AirlineViewModel);

@{
    ViewData["Title"] = "- Airline";
}

<div class="container">
    <div class="header">
        <a asp-controller="Home" asp-action="Index"><img src="/assets/left sidebar.png" alt="bar" /></a>
        <h1>Airlines</h1>
        <div class="header-divider"></div>
    </div>
    <section class="table-section">
        <div class="search-container">
            <form class="form-search" asp-controller="Airline" asp-action="Index" method="get">
                <input type="text" placeholder="search" name="search" />
                <select name="searchFilter" id="searchFilter">
                    <option value="">---</option>
                    <option value="Name">Name</option>
                    <option value="Founded">Founded</option>
                    <option value="Fleet_Size">Fleet Size</option>
                    <option value="Description">Description</option>
                </select>
                <button type="submit"><img src="~/assets/search.png" /></button>
            </form>
            <form class="form-filters" asp-controller="Airline" asp-action="Index" method="get">
                <label for="nameFilter">Filter by name:</label>
                <select class="filter-select" name="nameFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Name (ASC)</option>
                    <option value="DESC">Name (DESC)</option>
                </select>

                <label for="foundedFilter">Filter by founded: </label>
                <select class="filter-select" name="foundedFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Founded (ASC)</option>
                    <option value="DESC">Founded (DESC)</option>
                </select>

                <label for="fleetSizeFilter">Filter by Fleet Size: </label>
                <select class="filter-select" name="fleetSizeFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Fleet Size (ASC)</option>
                    <option value="DESC">Fleet Size (DESC)</option>
                </select>

                <label for="descriptionFilter">Filter by Description: </label>
                <select class="filter-select" name="descriptionFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Description (ASC)</option>
                    <option value="DESC">Description (DESC)</option>
                </select>

                <button type="submit">Submit</button>
            </form>
        </div>
        <div class="scrollable-table">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Founded</th>
                        <th>Fleet Size</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (AirlineViewModel airline in Model.Item1)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => airline.Name)</td>
                            <td>@Html.DisplayFor(modelItem => airline.Founded)</td>
                            <td>@Html.DisplayFor(modelItem => airline.FleetSize)</td>
                            <td>@Html.DisplayFor(modelItem => airline.Description)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </section>
    <button id="go-up-button" class="hidden">Go Up</button>
    <button class="orange-button" id="show-table-button">Hide Table</button>
    <button class="orange-button" id="show-form-button">Show Form</button>
    <section class="form-section" id="form-section">
        <form class="form-container" asp-action="Create">
            @if (ViewBag.Error != null)
            {
                <span class="span-error">@ViewBag.Error</span>
            }

            <div class="div-error-group" asp-validation-summary="All"></div>

            <fieldset class="form-fieldset">
                <legend>Add New Airline</legend>

                <div class="form-item">
                    <label asp-for="Item2.Name">Name</label>
                    <input type="text" id="name" name="name" asp-for="Item2.Name" value="@Model.Item2.Name"/>
                    <span id="name-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label asp-for="Item2.Founded">Founded</label>
                    <input type="date" id="founded" name="founded" asp-for="Item2.Founded" value="@Model.Item2.Founded" />
                    <span id="founded-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label asp-for="Item2.FleetSize">Fleet Size</label>
                    <input type="text" id="fleetSize" name="fleetSize" asp-for="Item2.FleetSize" value="@Model.Item2.FleetSize" />
                    <span id="fleetSize-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label asp-for="Item2.Description">Description</label>
                    <input type="text" id="description" name="description" asp-for="Item2.Description" value="@Model.Item2.Description" />
                    <span id="description-error" class="span-error"></span>
                </div>

                <input class="form-submit" type="submit" value="Submit">
            </fieldset>
        </form>
    </section>
</div>

@section Scripts {
    <script src="~/js/airline.js"></script>
    <script src="~/js/airlines/validation.js"></script>
    <script src="~/js/animation.js"></script>
    <partial name="_ValidationScriptsPartial" />
}