Airlines/AirlinesWeb/Models/Flight/FlightViewModel.cs
using AirlinesWeb.Models.Airport;
using AirlinesWeb.Models.Flight.Validation;
using System.ComponentModel.DataAnnotations;

namespace AirlinesWeb.Models.Flight;

public class FlightViewModel
{
    [Key]
    public int ID { get; set; }

    [Required(ErrorMessage = "Flight number is required")]
    [StringLength(6, ErrorMessage = "Flight number should be at most 6 characters long")]
    public string? FlightNumber { get; set; }

    [Required(ErrorMessage = "Price is required")]
    [Range(0.01, double.MaxValue, ErrorMessage = "Price should be a positive number")]
    public decimal Price { get; set; }

    [Required(ErrorMessage = "Departure date and time are required")]
    [DataType(DataType.DateTime)]
    [DepartureDateNotPast(ErrorMessage = "Departure date and time cannot be in the past")]
    public DateTime? DepartureDateTime { get; set; }

    [Required(ErrorMessage = "Arrival date and time are required")]
    [DataType(DataType.DateTime)]
    [ArrivalDateNotPast(ErrorMessage = "Arrival date and time cannot be in the past")]
    public DateTime? ArrivalDateTime { get; set; }

    public int FromAirportID { get; set; }

    [Required(ErrorMessage = "From airport name is required")]
    [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "From airport name should only contain letters and spaces")]
    public string? FromAirportName { get; set; }
    public AirportViewModel? FromAirport { get; set; }

    public int ToAirportID { get; set; }

    [Required(ErrorMessage = "To airport name is required")]
    [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "To airport name should only contain letters and spaces")]
    public string? ToAirportName { get; set; }

    public AirportViewModel? ToAirport { get; set; }

    public List<AirportViewModel>? Airports { get; set; }
}

Airlines/AirlinesWeb/Models/Flight/Validation/ArrivalDateNotPastAttribute.cs
using System.ComponentModel.DataAnnotations;

namespace AirlinesWeb.Models.Flight.Validation;

#pragma warning disable CS8765 // Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes).
public class ArrivalDateNotPastAttribute : ValidationAttribute
{
    protected override ValidationResult IsValid(object value, ValidationContext validationContext)
    {
        DateTime? arrivalDateTime = (DateTime?)value;

        if (arrivalDateTime == null || arrivalDateTime >= DateTime.Today)
        {
            return ValidationResult.Success!;
        }

        return new ValidationResult("Arrival date and time cannot be in the past");
    }
}

Airlines/AirlinesWeb/Models/Flight/Validation/DepartureDateNotPastAttribute.cs
using System.ComponentModel.DataAnnotations;

namespace AirlinesWeb.Models.Flight.Validation;
#pragma warning disable CS8765 // Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes).

public class DepartureDateNotPastAttribute : ValidationAttribute
{
    protected override ValidationResult IsValid(object value, ValidationContext validationContext)
    {
        DateTime? departureDateTime = (DateTime?)value;

        if (departureDateTime == null || departureDateTime >= DateTime.Today)
        {
            return ValidationResult.Success!;
        }

        return new ValidationResult("Departure date and time cannot be in the past");
    }
}

Airlines/AirlinesWeb/Controllers/FlightController.cs
using Airlines.Business.Services;
using Airlines.Business.Utils;
using Airlines.Persistence.Basic.DTO;
using Airlines.Persistence.Basic.EntitiesDB;
using AirlinesWeb.Models.Airport;
using AirlinesWeb.Models.Flight;
using Microsoft.AspNetCore.Mvc;

namespace AirlinesWeb.Controllers;

#pragma warning disable IDE0290 // Use primary constructor

public class FlightController : Controller
{
    private readonly IFlightService _flightService;
    private readonly IAirportService _airportService;

    public FlightController(IFlightService flightService, IAirportService airportService)
    {
        _flightService = flightService;
        _airportService = airportService;
    }

    public async Task<IActionResult> Index()
    {
        var flightNumberFilterValue = HttpContext.Request.Query["flightNumberFilter"].ToString();
        var fromFilterValue = HttpContext.Request.Query["fromFilter"].ToString();
        var toFilterValue = HttpContext.Request.Query["toFilter"].ToString();
        var priceFilterValue = HttpContext.Request.Query["priceFilter"].ToString();
        var departureFilterValue = HttpContext.Request.Query["departureFilter"].ToString();
        var arrivalFilterValue = HttpContext.Request.Query["arrivalFilter"].ToString();
        var searchValue = HttpContext.Request.Query["search"].ToString();
        var searchFilterValue = HttpContext.Request.Query["searchFilter"].ToString();

        List<Flight> allFlights = !string.IsNullOrEmpty(searchValue)
            ? await _flightService.GetAllFlightsFromDB(searchValue, searchFilterValue)
            : await _flightService.GetAllFlightsFromDB();

        allFlights = ServicesUtils.ApplySorting(allFlights, flightNumberFilterValue, x => x.FlightNumber);
        allFlights = ServicesUtils.ApplySorting(allFlights, fromFilterValue, x => x.FromAirport.Name);
        allFlights = ServicesUtils.ApplySorting(allFlights, toFilterValue, x => x.ToAirport.Name);
        allFlights = ServicesUtils.ApplySorting(allFlights, priceFilterValue, x => x.Price);
        allFlights = ServicesUtils.ApplySorting(allFlights, departureFilterValue, x => x.DepartureDateTime);
        allFlights = ServicesUtils.ApplySorting(allFlights, arrivalFilterValue, x => x.ArrivalDateTime);

        List<FlightViewModel> allFlightsViewModels = allFlights.Select(x => new FlightViewModel
        {
            ID = x.ID,
            FlightNumber = x.FlightNumber,
            Price = x.Price,
            DepartureDateTime = x.DepartureDateTime,
            ArrivalDateTime = x.ArrivalDateTime,
            FromAirport = new AirportViewModel
            {
                ID = x.FromAirport.ID,
                City = x.FromAirport.City,
                Country = x.FromAirport.Country,
                Code = x.FromAirport.Code,
                Founded = x.FromAirport.Founded,
                Name = x.FromAirport.Name,
                RunwaysCount = x.FromAirport.RunwaysCount
            },
            ToAirport = new AirportViewModel
            {
                ID = x.ToAirport.ID,
                City = x.ToAirport.City,
                Country = x.ToAirport.Country,
                Code = x.ToAirport.Code,
                Founded = x.ToAirport.Founded,
                Name = x.ToAirport.Name,
                RunwaysCount = x.ToAirport.RunwaysCount
            }
        }).ToList();

        return View((allFlightsViewModels, new FlightViewModel()));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] FlightViewModel flightViewModel)
    {
        var allAiports = await _airportService.GetAllAirportsFromDB();
        List<Flight> allFlights = await _flightService.GetAllFlightsFromDB();

        flightViewModel.Airports = allAiports.Select(a => new AirportViewModel
        {
            ID = a.ID,
            City = a.City,
            Country = a.Country,
            Code = a.Code,
            Founded = a.Founded,
            Name = a.Name,
            RunwaysCount = a.RunwaysCount
        }).ToList();

        //Since we are not having logic for
        //AircraftModelId and AirlineId for the moment
        //I am assiging 15 as AircraftModelId and 17 for AirlineId for each record

        FlightDTO flightDTO = new FlightDTO(
           flightViewModel.FlightNumber!,
           15,
           17,
           flightViewModel.Airports.FirstOrDefault(a => a.Name!.Contains(flightViewModel.FromAirportName!, StringComparison.OrdinalIgnoreCase))!.ID,
           flightViewModel.Airports.FirstOrDefault(a => a.Name!.Contains(flightViewModel.ToAirportName!, StringComparison.OrdinalIgnoreCase))!.ID,
           flightViewModel.Price,
           flightViewModel.DepartureDateTime,
           flightViewModel.ArrivalDateTime
           );

        List<FlightViewModel> allFlightsViewModel = allFlights.Select(x => new FlightViewModel
        {
            ID = x.ID,
            FlightNumber = x.FlightNumber,
            Price = x.Price,
            DepartureDateTime = x.DepartureDateTime,
            ArrivalDateTime = x.ArrivalDateTime,
            FromAirport = new AirportViewModel
            {
                ID = x.FromAirport.ID,
                City = x.FromAirport.City,
                Country = x.FromAirport.Country,
                Code = x.FromAirport.Code,
                Founded = x.FromAirport.Founded,
                Name = x.FromAirport.Name,
                RunwaysCount = x.FromAirport.RunwaysCount
            },
            ToAirport = new AirportViewModel
            {
                ID = x.ToAirport.ID,
                City = x.ToAirport.City,
                Country = x.ToAirport.Country,
                Code = x.ToAirport.Code,
                Founded = x.ToAirport.Founded,
                Name = x.ToAirport.Name,
                RunwaysCount = x.ToAirport.RunwaysCount
            }
        }).ToList();

        if (!ModelState.IsValid)
        {
            ViewBag.Error = "Invalid flight create entity";

            return View(nameof(Index), (allFlightsViewModel, flightViewModel));
        }

        if (await _flightService.AddFlightToDB(flightDTO) == null)
        {
            ViewBag.Error = "Invalid flight create entity";
            return View(nameof(Index), (allFlightsViewModel, flightViewModel));
        }

        return RedirectToAction(nameof(Index));
    }
}

Airlines/AirlinesWeb/Views/Flight/Index.cshtml
@using AirlinesWeb.Models.Flight

@model (List<FlightViewModel>, FlightViewModel);

@{
    ViewData["Title"] = "- Flight";
}

<div class="container">
    <div class="header">
        <a asp-controller="Home" asp-action="Index"><img src="/assets/left sidebar.png" alt="bar" /></a>
        <h1>Flights</h1>
        <div class="header-divider"></div>
    </div>
    <section class="table-section">
        <div class="search-container">
            <form class="form-search" asp-controller="Flight" asp-action="Index" method="get">
                <input type="text" placeholder="search" name="search" />
                <select name="searchFilter" id="searchFilter">
                    <option value="">---</option>
                    <option value="Flight_Number">Flight Number</option>
                    <option value="From">From</option>
                    <option value="To">To</option>
                    <option value="Price">Price</option>
                    <option value="Departure">Departure</option>
                    <option value="Arrival">Arrival</option>
                </select>
                <button type="submit"><img src="~/assets/search.png" /></button>
            </form>
            <form class="form-filters" asp-controller="Flight" asp-action="Index" method="get">
                <label for="flightNumberFilter">Filter by flight number:</label>
                <select class="filter-select" name="flightNumberFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Flight Number (ASC)</option>
                    <option value="DESC">Flight Number (DESC)</option>
                </select>

                <label for="fromFilter">Filter by from:</label>
                <select class="filter-select" name="fromFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">From (ASC)</option>
                    <option value="DESC">From (DESC)</option>
                </select>

                <label for="toFilter">Filter by to:</label>
                <select class="filter-select" name="toFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">To (ASC)</option>
                    <option value="DESC">To (DESC)</option>
                </select>

                <label for="priceFilter">Filter by price:</label>
                <select class="filter-select" name="priceFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Price (ASC)</option>
                    <option value="DESC">Price (DESC)</option>
                </select>

                <label for="departureFilter">Filter by departure:</label>
                <select class="filter-select" name="departureFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Departure (ASC)</option>
                    <option value="DESC">Departure (DESC)</option>
                </select>

                <label for="arrivalFilter">Filter by arrival:</label>
                <select class="filter-select" name="arrivalFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Arrival (ASC)</option>
                    <option value="DESC">Arrival (DESC)</option>
                </select>

                <button type="submit">Submit</button>
            </form>
        </div>
        <div class="scrollable-table">
            <table class="table">
                <thead>
                    <tr>
                        <th>Flight Number</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Price</th>
                        <th>Departure</th>
                        <th>Arrival</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (FlightViewModel flight in Model.Item1)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => flight.FlightNumber)</td>
                            <td>@Html.DisplayFor(modelItem => flight.FromAirport!.Name)</td>
                            <td>@Html.DisplayFor(modelItem => flight.ToAirport!.Name)</td>
                            <td>@Html.DisplayFor(modelItem => flight.Price)</td>
                            <td>@Html.DisplayFor(modelItem => flight.DepartureDateTime)</td>
                            <td>@Html.DisplayFor(modelItem => flight.ArrivalDateTime)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </section>
    <button id="go-up-button" class="hidden">Go Up</button>
    <button class="orange-button" id="show-table-button">Hide Table</button>
    <button class="orange-button" id="show-form-button">Show Form</button>
    <section class="form-section" id="form-section">
        <form class="form-container" asp-action="Create">
            @if (ViewBag.Error != null)
            {
                <span class="span-error">@ViewBag.Error</span>
            }

            <div class="div-error-group" asp-validation-summary="All"></div>

            <fieldset class="form-fieldset">
                <legend>Add New Flight</legend>

                <div class="form-item">
                    <label for="flightNumber">Flight number</label>
                    <input type="text" id="flightNumber" name="flightNumber" asp-for="Item2.FlightNumber" value="@Model.Item2.FlightNumber" />
                    <span id="flightNumber-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label for="fromAirport">From</label>
                    <input type="text" id="fromAirportName" name="fromAirportName" asp-for="Item2.FromAirportName" value="@Model.Item2.FromAirportName"/>
                    <span id="fromAirportName-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label for="toAirport">To</label>
                    <input type="text" id="toAirportName" name="toAirportName" asp-for="Item2.ToAirportName" value="@Model.Item2.ToAirportName" />
                    <span id="toAirportName-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label for="price">Price</label>
                    <input type="number" id="price" name="price" asp-for="Item2.Price" value="@Model.Item2.Price" />
                    <span id="price-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label for="departureDatetime">Departure date</label>
                    <input type="datetime-local" id="departureDatetime" name="departureDatetime" asp-for="Item2.DepartureDateTime" value="@Model.Item2.DepartureDateTime" />
                    <span asp-validation-for="Item2.DepartureDateTime"></span>
                    <span id="departureDateTime-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label for="arrivalDatetime">Arrival date</label>
                    <input type="datetime-local" id="arrivalDatetime" name="arrivalDatetime" asp-for="Item2.ArrivalDateTime" value="@Model.Item2.ArrivalDateTime" />
                    <span id="arrivalDatetime-error" class="span-error"></span>
                </div>

                <input class="form-submit" type="submit" value="Submit">
            </fieldset>
        </form>
    </section>
</div>

@section Scripts {
    <script src="~/js/airline.js"></script>
    <script src="~/js/flights/validation.js"></script>
    <script src="~/js/animation.js"></script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}