Airlines/AirlinesWeb/Models/Airport/AirportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AirlinesWeb.Models.Airport;

public class AirportViewModel
{
    [Key]
    public int ID { get; set; }

    [Required(ErrorMessage = "Name is required")]
    [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "Name should only contain letters and spaces")]
    public string? Name { get; set; }

    [Required(ErrorMessage = "Country is required")]
    [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "Country should only contain letters and spaces")]
    public string? Country { get; set; }

    [Required(ErrorMessage = "City is required")]
    [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "City should only contain letters and spaces")]
    public string? City { get; set; }

    [Required(ErrorMessage = "Code is required")]
    [RegularExpression(@"^[A-Za-z]+$", ErrorMessage = "Code should only contain letters")]
    [StringLength(3, MinimumLength = 3, ErrorMessage = "Code should be exactly 3 characters long")]
    public string? Code { get; set; }

    [Required(ErrorMessage = "Runways count is required")]
    [RegularExpression(@"^\d+$", ErrorMessage = "Runways count should be a positive integer")]
    public int? RunwaysCount { get; set; }

    [DataType(DataType.Date)]
    [Required(ErrorMessage = "Founded date is required")]
    public DateOnly? Founded { get; set; }
}

Airlines/AirlinesWeb/Controllers/AirportController.cs
using Airlines.Business.Services;
using Airlines.Business.Utils;
using Airlines.Persistence.Basic.DTO;
using Airlines.Persistence.Basic.EntitiesDB;
using AirlinesWeb.Models.Airport;
using Microsoft.AspNetCore.Mvc;

namespace AirlinesWeb.Controllers;

#pragma warning disable IDE0290 // Use primary constructor
#pragma warning disable IDE0021 // Use expression body for constructor
public class AirportController : Controller
{
    private readonly IAirportService _airportService;

    public AirportController(IAirportService airportService)
    {
        _airportService = airportService;
    }

    public async Task<IActionResult> Index()
    {
        var nameFilterValue = HttpContext.Request.Query["nameFilter"].ToString();
        var countryFilterValue = HttpContext.Request.Query["countryFilter"].ToString();
        var cityFilterValue = HttpContext.Request.Query["cityFilter"].ToString();
        var codeFilterValue = HttpContext.Request.Query["codeFilter"].ToString();
        var runwaysFilterValue = HttpContext.Request.Query["runwaysFilter"].ToString();
        var foundedFilterValue = HttpContext.Request.Query["foundedFilter"].ToString();

        var searchValue = HttpContext.Request.Query["search"].ToString();
        var searchFilter = HttpContext.Request.Query["searchFilter"].ToString();

        List<Airport> allAirports = !string.IsNullOrEmpty(searchValue)
            ? await _airportService.GetAllAirportsFromDB(searchValue, searchFilter)
            : await _airportService.GetAllAirportsFromDB();

        allAirports = ServicesUtils.ApplySorting(allAirports, nameFilterValue, x => x.Name);
        allAirports = ServicesUtils.ApplySorting(allAirports, countryFilterValue, x => x.Country);
        allAirports = ServicesUtils.ApplySorting(allAirports, cityFilterValue, x => x.City);
        allAirports = ServicesUtils.ApplySorting(allAirports, codeFilterValue, x => x.Code);
        allAirports = ServicesUtils.ApplySorting(allAirports, runwaysFilterValue, x => x.RunwaysCount!);
        allAirports = ServicesUtils.ApplySorting(allAirports, foundedFilterValue, x => x.Founded!);

        List<AirportViewModel> allAiprortsViewModels = allAirports.Select(x => new AirportViewModel
        {
            ID = x.ID,
            Name = x.Name,
            City = x.City,
            Code = x.Code,
            Country = x.Country,
            RunwaysCount = x.RunwaysCount,
            Founded = x.Founded
        }).ToList();


        return View((allAiprortsViewModels, new AirportViewModel()));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] AirportViewModel airportViewModel)
    {
        AirportDTO airportDTO = new AirportDTO(
            airportViewModel.Name,
            airportViewModel.Country,
            airportViewModel.City,
            airportViewModel.Code,
            airportViewModel.RunwaysCount,
            airportViewModel.Founded
           );

        List<Airport> allAirports = await _airportService.GetAllAirportsFromDB();

        List<AirportViewModel> allAiprortsViewModels = allAirports.Select(x => new AirportViewModel
        {
            ID = x.ID,
            Name = x.Name,
            City = x.City,
            Code = x.Code,
            Country = x.Country,
            RunwaysCount = x.RunwaysCount,
            Founded = x.Founded
        }).ToList();


        if (!ModelState.IsValid)
        {
            ViewBag.Error = "Invalid airport create entity";

            return View(nameof(Index), (allAiprortsViewModels, airportViewModel));
        }

        if (await _airportService.AddAirportToDB(airportDTO) == null)
        {
            ViewBag.Error = "Invalid airport create entity";
            return View(nameof(Index), (allAiprortsViewModels, airportViewModel));
        }

        return RedirectToAction(nameof(Index));
    }
}

Airlines/AirlinesWeb/Views/Airport/Index.cshtml
@using AirlinesWeb.Models.Airport

@model (List<AirportViewModel>, AirportViewModel);

@{
    ViewData["Title"] = "- Airport";
}

<div class="container">
    <div class="header">
        <a asp-controller="Home" asp-action="Index"><img src="/assets/left sidebar.png" alt="bar" /></a>
        <h1>Airports</h1>
        <div class="header-divider"></div>
    </div>
    <section class="table-section">
        <div class="search-container">
            <form class="form-search" asp-controller="Airport" asp-action="Index" method="get">
                <input type="text" placeholder="search" name="search" />
                <select name="searchFilter" id="searchFilter">
                    <option value="">---</option>
                    <option value="Name">Name</option>
                    <option value="City">City</option>
                    <option value="Code">Code</option>
                    <option value="Runways">Runways</option>
                    <option value="Founded">Founded</option>
                </select>
                <button type="submit"><img src="~/assets/search.png" /></button>
            </form>
            <form class="form-filters" asp-controller="Airport" asp-action="Index" method="get">
                <label for="nameFilter">Filter by name:</label>
                <select class="filter-select" name="nameFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Name (ASC)</option>
                    <option value="DESC">Name (DESC)</option>
                </select>

                <label for="countryFilter">Filter by country:</label>
                <select class="filter-select" name="countryFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Country (ASC)</option>
                    <option value="DESC">Country (DESC)</option>
                </select>

                <label for="cityFilter">Filter by city:</label>
                <select class="filter-select" name="cityFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">City (ASC)</option>
                    <option value="DESC">City (DESC)</option>
                </select>

                <label for="codeFilter">Filter by code:</label>
                <select class="filter-select" name="codeFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Code (ASC)</option>
                    <option value="DESC">Code (DESC)</option>
                </select>

                <label for="runwaysFilter">Filter by runways:</label>
                <select class="filter-select" name="runwaysFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Runways (ASC)</option>
                    <option value="DESC">Runways (DESC)</option>
                </select>

                <label for="foundedFilter">Filter by founded:</label>
                <select class="filter-select" name="foundedFilter" id="filters">
                    <option value="">---</option>
                    <option value="ASC">Founded (ASC)</option>
                    <option value="DESC">Founded (DESC)</option>
                </select>

                <button type="submit">Submit</button>
            </form>
        </div>
        <div class="scrollable-table">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Country</th>
                        <th>City</th>
                        <th>Code</th>
                        <th>Runways</th>
                        <th>Founded</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (AirportViewModel airport in Model.Item1)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => airport.Name)</td>
                            <td>@Html.DisplayFor(modelItem => airport.Country)</td>
                            <td>@Html.DisplayFor(modelItem => airport.City)</td>
                            <td>@Html.DisplayFor(modelItem => airport.Code)</td>
                            <td>@Html.DisplayFor(modelItem => airport.RunwaysCount)</td>
                            <td>@Html.DisplayFor(modelItem => airport.Founded)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </section>
    <button id="go-up-button" class="hidden">Go Up</button>
    <button class="orange-button" id="show-table-button">Hide Table</button>
    <button class="orange-button" id="show-form-button">Show Form</button>
    <section class="form-section" id="form-section">
        <form class="form-container" asp-action="Create">
            @if (ViewBag.Error != null)
            {
                <span class="span-error">@ViewBag.Error</span>
            }

            <div class="div-error-group" asp-validation-summary="All"></div>

            <fieldset class="form-fieldset">
                <legend>Add New Airport</legend>

                <div class="form-item">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" asp-for="Item2.Name" value="@Model.Item2.Name" />
                    <span id="name-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label for="country">Country</label>
                    <input type="text" id="country" name="country" asp-for="Item2.Country" value="@Model.Item2.Country" />
                    <span id="country-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label for="city">City</label>
                    <input type="text" id="city" name="city" asp-for="Item2.City" value="@Model.Item2.City" />
                    <span id="city-error" class="span-error"></span>
                </div>
                <div class="form-item">
                    <label for="code">Code</label>
                    <input type="text" id="code" name="code" asp-for="Item2.Code" value="@Model.Item2.Code" />
                    <span id="code-error" class="span-error"></span>
                </div>
                <div class="form-item">
                    <label for="runwaysCount">Runways</label>
                    <input type="number" id="runwaysCount" name="runwaysCount" asp-for="Item2.RunwaysCount" value="@Model.Item2.RunwaysCount" />
                    <span id="runwaysCount-error" class="span-error"></span>
                </div>

                <div class="form-item">
                    <label for="founded">Founded</label>
                    <input type="date" id="founded" name="founded" asp-for="Item2.Founded" value="@Model.Item2.Founded" />
                    <span id="founded-error" class="span-error"></span>
                </div>

                <input class="form-submit" type="submit" value="Submit">
            </fieldset>
        </form>
    </section>
</div>

@section Scripts {
    <script src="~/js/airline.js"></script>
    <script src="~/js/airports/validation.js"></script>
    <script src="~/js/animation.js"></script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}